title:  I'm Zdnuist
description: > # this means to ignore newlines until "baseurl:"
  
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Zdnuist # add your name
author-img: zdnuist.jpg # add your photo
about-author: I am a android developer . # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: zdnuist  # add your Github handle
linkedin: # add your Linkedin handle
email: 619058238@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
